version: '3'

services:
  mongo:
    image: mongo
    container_name: camic-mongo
    ports:
      -"27017"
  data:
    build: "https://github.com/birm/caMicData.git"
    container_name: camic-data
    environment:
      - MONGO="camic-mongo:27017"
  iip:
    build: "https://github.com/camicroscope/iipImage.git"
    container_name: camic-iip
  viewer:
    build: "./viewer"
    container_name: "camic-viewer"
